&ACCESS RVP
&REL 2
&COMMENT USER specified PLC program
DEF  realTimeIOs ( )
   LOOP
      $RECIPE.recipeNum = ByNumeroReceta
      IF ($RECIPE.recipeNum > 0) THEN
      ;Carga parametos de receta desde PLC
      $RECIPE.diametroHexagono = ByDiametroHexagono
      $RECIPE.diametroRosca = ByDiametroRosca
      $RECIPE.lHexagono = ByLongitudHexagono
      $RECIPE.lTotal = wLongitudTotal
      $RECIPE.lOffsetCBP = wLongitudOffsetCintaBP
      $RECIPE.lOffsetCIND = wLongitudOffsetIND
      
      
      ;Carga datos de offset en pick(Base1) y place(Base5)
      $RECIPE.PiO = RECIPE_DATA[$RECIPE.recipeNum].PiO
      $RECIPE.PlO = RECIPE_DATA[$RECIPE.recipeNum].PlO
      WAIT SEC 0.1
      ENDIF

   ENDLOOP
END
